# -*- coding: utf-8 -*-
"""E-commerce .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JjupYPj0LZxjeRLvYBEh_0CqeGfeXRo7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df = pd.read_csv("/content/Pakistan Largest Ecommerce Dataset.csv")

df

df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df

df = df.dropna(how='all')
df

df.info()

df.isnull().sum()

df = df.drop('sales_commission_code', axis=1)

df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

df.isnull().sum()

df.duplicated().sum()

df = df.replace(r'^\s*\\N\s*$', np.nan, regex=True)
df.isnull().sum()

df['category_name_1'] = df['category_name_1'].fillna('Others')
df = df.dropna(subset=['status'])

df.isnull().sum()

df.duplicated().sum()

df.info()

df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')
df['Working Date'] = pd.to_datetime(df['Working Date'], errors='coerce')
df['Customer Since'] = pd.to_datetime(df['Customer Since'], format='%Y-%m', errors='coerce')

df['M-Y'] = df['M-Y'].astype(str).str.strip()

df['increment_id'] = pd.to_numeric(df['increment_id'], errors='coerce').astype('Int64')
df['Customer ID'] = pd.to_numeric(df['Customer ID'], errors='coerce').astype('Int64')
df['item_id'] = pd.to_numeric(df['item_id'], errors='coerce').astype('Int64')

df.columns = df.columns.str.strip()

df['MV'] = df['MV'].dropna().astype(str).str.replace(r'[^0-9.]', '', regex=True)
df['MV'] = pd.to_numeric(df['MV'], errors='coerce')

df['Year'] = pd.to_numeric(df['Year'], errors='coerce').astype('Int64')
df['Month'] = pd.to_numeric(df['Month'], errors='coerce').astype('Int64')
df['qty_ordered'] = pd.to_numeric(df['qty_ordered'], errors='coerce').astype('Int64')

df.info()

df.isnull().sum()

df['MV'] = df['MV'].fillna(df['MV'].median())

df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

df.isnull().sum()

df

numeric_cols = ['price', 'qty_ordered', 'grand_total', 'discount_amount', 'MV']

outlier_summary = []
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    count = ((df[col] < lower) | (df[col] > upper)).sum()
    pct = (count / len(df)) * 100

    outlier_summary.append({
        'Metric': col,
        'Min': df[col].min(),
        'Max': df[col].max(),
        'Lower Bound': round(lower, 2),
        'Upper Bound': round(upper, 2),
        'Outliers Count': count,
        'Outliers %': round(pct, 2)
    })

outlier_df = pd.DataFrame(outlier_summary)
print(outlier_df.to_string(index=False))

negative_grand_total_count = (df['grand_total'] < 0).sum()
negative_discount_amount = (df['discount_amount'] < 0).sum()
prices_equal_to_zero = (df['price'] == 0).sum()
print(f"Number of negative values in 'grand_total': {negative_grand_total_count}")
print(f"Number of negative values in 'discount_amount': {negative_discount_amount}")
print(f"number of zeros in 'price': {prices_equal_to_zero}")

# Remove zero prices and negative grand totals and discounts
df = df[(df['price'] > 0) & (df['grand_total'] >= 0) & (df['discount_amount'] >= 0)]
df.reset_index(drop=True, inplace=True)

df.info()

df

extreme_orders = df[df['grand_total'] > 1000000]
print(f"Orders > 1,000,000: {len(extreme_orders)}")

print(df['grand_total'].nlargest(30).to_string())

df = df[df['grand_total'] != 17888000.0]

print(df['price'].nlargest(30).to_string())

print(df['MV'].nlargest(30).to_string())

outlier_summary = []
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    count = ((df[col] < lower) | (df[col] > upper)).sum()
    pct = (count / len(df)) * 100

    outlier_summary.append({
        'Metric': col,
        'Min': df[col].min(),
        'Max': df[col].max(),
        'Lower Bound': round(lower, 2),
        'Upper Bound': round(upper, 2),
        'Outliers Count': count,
        'Outliers %': round(pct, 2)
    })

outlier_df = pd.DataFrame(outlier_summary)
print(outlier_df.to_string(index=False))

#detect duplicate in names

text_cols = ['status', 'payment_method', 'category_name_1', 'BI Status']

#remove any spaces for a clean name
for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

for col in text_cols:
    print(f"\n--- Unique values in {col} ---")
    print(df[col].unique())

ref_count = (df['BI Status'] == '#REF!').sum()
print(f"Rows with #REF! in BI Status: {ref_count}")

print(df[df['BI Status'] == '#REF!'][['status', 'grand_total', 'BI Status']].head())

# Standardize payment_method to lowercase
df['payment_method'] = df['payment_method'].str.lower()

# 1. Lowercase payment methods to standardize names
df['payment_method'] = df['payment_method'].str.lower()

# 2. Map or replace '#REF!' in BI Status (Replacing with 'Unknown' or mapping based on status)
df['BI Status'] = df['BI Status'].replace('#REF!', 'Unknown')

# Confirm updated unique values
print("--- Cleaned BI Status ---")
print(df['BI Status'].unique())

print("\n--- Cleaned Payment Methods ---")
print(df['payment_method'].unique())

# exact duplicate rows across all columns
exact_dupes = df.duplicated().sum()
print(f"Exact duplicate rows: {exact_dupes}")

# Remove exact duplicates
if exact_dupes > 0:
    df = df.drop_duplicates()

# duplicate order items (Same order ID + Same Item ID)
item_dupes = df.duplicated(subset=['increment_id', 'item_id']).sum()
print(f"Duplicate item entries within same order: {item_dupes}")

df.to_csv('cleaned_ecommerce_data.csv', index=False)

df.head(30)

plt.figure(figsize=(12, 6))
monthly_rev = df.groupby(['Year', 'Month'])['grand_total'].sum().reset_index()
monthly_rev['Date'] = pd.to_datetime(monthly_rev[['Year', 'Month']].assign(DAY=1))

sns.lineplot(data=monthly_rev, x='Date', y='grand_total', marker='o', linewidth=2, color='b')
plt.title('Monthly Realized Revenue Trajectory', fontsize=14, fontweight='bold')
plt.ylabel('Total Revenue')
plt.xlabel('Month')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 8))
cat_rev = df.groupby('category_name_1')['grand_total'].sum().sort_values(ascending=False).head(10)
sns.barplot(x=cat_rev.values, y=cat_rev.index, palette="viridis")
plt.title('Top 10 Categories by Realized Revenue', fontsize=14, fontweight='bold')
plt.xlabel('Total Revenue')
plt.ylabel('Product Category')
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 8))
aov_cat = df.groupby('category_name_1')['grand_total'].mean().sort_values(ascending=False).head(10)
sns.barplot(x=aov_cat.values, y=aov_cat.index, hue=aov_cat.index, palette="mako", legend=False)
plt.title(' Average Order Value (AOV) by Category', fontsize=14, fontweight='bold')
plt.xlabel('Average Spend per Order')
plt.ylabel('Product Category')
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 8))
top_skus = df.groupby('sku')['qty_ordered'].sum().sort_values(ascending=False).head(10)
sns.barplot(x=top_skus.values, y=top_skus.index, hue=top_skus.index, palette="rocket", legend=False)
plt.title('Top 10 Highest Volume Products (Inventory Focus)', fontsize=14, fontweight='bold')
plt.xlabel('Total Quantity Sold')
plt.ylabel('SKU')
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 8))
status_counts = df['status'].value_counts().head(8)
sns.barplot(x=status_counts.values, y=status_counts.index, hue=status_counts.index, palette="Reds_r", legend=False)
plt.title('Order Status Breakdown (Fulfillment Health)', fontsize=14, fontweight='bold')
plt.xlabel('Number of Orders')
plt.ylabel('Status')
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 8))
payment_counts = df['payment_method'].value_counts().head(10)
sns.barplot(x=payment_counts.values, y=payment_counts.index, hue=payment_counts.index, palette="crest", legend=False)
plt.title('Most Popular Payment Methods', fontsize=14, fontweight='bold')
plt.xlabel('Number of Transactions')
plt.ylabel('Payment Method')
plt.grid(True)
plt.tight_layout()
plt.show()

payment_risk = df.groupby('payment_method').agg(
    Total_Orders=('increment_id', 'nunique'),
    Canceled_Orders=('status', lambda x: (x == 'canceled').sum())
)
payment_risk = payment_risk[payment_risk['Total_Orders'] > 1000].reset_index()
payment_risk['Cancel_Rate_%'] = (payment_risk['Canceled_Orders'] / payment_risk['Total_Orders']) * 100
payment_risk = payment_risk.sort_values('Cancel_Rate_%', ascending=False)

fig3 = px.bar(payment_risk, x='Cancel_Rate_%', y='payment_method', orientation='h',
              title='Cancellation Risk by Payment Method (High = Bad)',
              labels={'Cancel_Rate_%': 'Cancellation Rate (%)', 'payment_method': 'Payment Method'},
              color='Cancel_Rate_%', color_continuous_scale='Reds')
fig3.update_layout(yaxis={'categoryorder':'total ascending'})
fig3.show()

df['DayOfWeek'] = df['created_at'].dt.day_name()
days_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
daily_traffic = df.groupby('DayOfWeek')['increment_id'].nunique().reindex(days_order).reset_index()

fig4 = px.bar(daily_traffic, x='DayOfWeek', y='increment_id',
              title='Peak Shopping Days (Optimize Ad Spend)',
              labels={'increment_id': 'Total Unique Orders', 'DayOfWeek': 'Day of the Week'},
              color='increment_id', color_continuous_scale='Blues')
fig4.show()

df.groupby('category_name_1').agg(
    Revenue=('grand_total', 'sum'),
    Discounts=('discount_amount', 'sum'))

discount_impact = df.groupby('category_name_1').agg(
    Revenue=('grand_total', 'sum'),
    Discounts=('discount_amount', 'sum')
).sort_values('Revenue', ascending=False).head(10).reset_index()

fig5 = px.bar(discount_impact, x='category_name_1', y=['Revenue', 'Discounts'], barmode='group',
              title=' Revenue vs. Discount Expenditure by Category',
              labels={'value': 'Monetary Value', 'category_name_1': 'Category', 'variable': 'Metric'},
              color_discrete_map={'Revenue': '#2CA02C', 'Discounts': '#D62728'})
fig5.show()

df['First_Purchase_Date'] = df.groupby('Customer ID')['created_at'].transform('min')
df['Customer_Type'] = np.where(df['created_at'] == df['First_Purchase_Date'], 'New', 'Returning')

retention_rev = df.groupby(['Year', 'Month', 'Customer_Type'])['grand_total'].sum().reset_index()
retention_rev['Date'] = pd.to_datetime(retention_rev[['Year', 'Month']].assign(DAY=1))

fig3 = px.area(retention_rev, x='Date', y='grand_total', color='Customer_Type',
               title='Revenue from New vs Returning Customers (Area Chart)',
               labels={'grand_total': 'Total Revenue', 'Date': 'Timeline'},
               color_discrete_map={'New': '#1f77b4', 'Returning': '#2ca02c'})
fig3.show()

df['Price_Tier'] = pd.qcut(df['price'], q=4, labels=['Low', 'Medium-Low', 'Medium-High', 'Premium'])
tier_rev = df.groupby('Price_Tier', observed=False)['grand_total'].sum().reset_index()

fig5 = px.pie(tier_rev, values='grand_total', names='Price_Tier', hole=0.4,
              title='Revenue Distribution by Price Tier (Donut Chart)',
              color_discrete_sequence=px.colors.sequential.Plasma)
fig5.show()

df_sales = df[df['status'].isin(['complete', 'received', 'closed'])].copy()


top_statuses = df['status'].value_counts().nlargest(5).reset_index()
top_statuses.columns = ['Order Status', 'Total Orders']

fig1 = px.funnel(top_statuses, x='Total Orders', y='Order Status',
                 title='Order Fulfillment Survival Rate',
                 color_discrete_sequence=['#1f77b4'])
fig1.show()

bubble_data = df_sales.groupby('category_name_1').agg(
    Total_Orders=('increment_id', 'nunique'),
    Total_Revenue=('grand_total', 'sum'),
    AOV=('grand_total', 'mean')
).reset_index()

fig2 = px.scatter(bubble_data, x='Total_Orders', y='Total_Revenue',
                  size='AOV', color='category_name_1', hover_name='category_name_1',
                  title=' Category Performance Matrix (Volume vs Revenue vs AOV)',
                  labels={'Total_Orders': 'Number of Orders Sold', 'Total_Revenue': 'Total Cash Generated'},
                  size_max=50)
fig2.show()

top_5_cats = df_sales['category_name_1'].value_counts().nlargest(5).index
box_data = df_sales[df_sales['category_name_1'].isin(top_5_cats)]

fig3 = px.box(box_data, x='category_name_1', y='grand_total', color='category_name_1',
              title='Expected Order Value Range by Top Categories',
              labels={'category_name_1': 'Category', 'grand_total': 'Order Total'},
              points="outliers")
fig3.update_yaxes(range=[0, box_data['grand_total'].quantile(0.95)])
fig3.show()

daily_revenue = df_sales.groupby(df_sales['created_at'].dt.date)['grand_total'].sum().reset_index()
daily_revenue['Cumulative_Revenue'] = daily_revenue['grand_total'].cumsum()

fig5 = px.line(daily_revenue, x='created_at', y='Cumulative_Revenue',
               title='Cumulative Business Revenue Growth Over Time',
               labels={'created_at': 'Date', 'Cumulative_Revenue': 'Total Accumulated Revenue'},
               color_discrete_sequence=['#2ca02c'])
fig5.update_traces(line=dict(width=3))
fig5.show()

df.info(
)

